/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mars.apacheavro.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FileChunk extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3017133439449625703L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FileChunk\",\"namespace\":\"com.mars.apacheavro.dto\",\"fields\":[{\"name\":\"fileId\",\"type\":\"string\"},{\"name\":\"fileName\",\"type\":\"string\"},{\"name\":\"chunkIndex\",\"type\":\"int\"},{\"name\":\"totalChunks\",\"type\":\"int\"},{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"checksumSha256\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FileChunk> ENCODER =
      new BinaryMessageEncoder<FileChunk>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FileChunk> DECODER =
      new BinaryMessageDecoder<FileChunk>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FileChunk> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FileChunk> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FileChunk>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FileChunk to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FileChunk from a ByteBuffer. */
  public static FileChunk fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence fileId;
  @Deprecated public java.lang.CharSequence fileName;
  @Deprecated public int chunkIndex;
  @Deprecated public int totalChunks;
  @Deprecated public java.nio.ByteBuffer data;
  @Deprecated public java.lang.CharSequence checksumSha256;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FileChunk() {}

  /**
   * All-args constructor.
   * @param fileId The new value for fileId
   * @param fileName The new value for fileName
   * @param chunkIndex The new value for chunkIndex
   * @param totalChunks The new value for totalChunks
   * @param data The new value for data
   * @param checksumSha256 The new value for checksumSha256
   */
  public FileChunk(java.lang.CharSequence fileId, java.lang.CharSequence fileName, java.lang.Integer chunkIndex, java.lang.Integer totalChunks, java.nio.ByteBuffer data, java.lang.CharSequence checksumSha256) {
    this.fileId = fileId;
    this.fileName = fileName;
    this.chunkIndex = chunkIndex;
    this.totalChunks = totalChunks;
    this.data = data;
    this.checksumSha256 = checksumSha256;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fileId;
    case 1: return fileName;
    case 2: return chunkIndex;
    case 3: return totalChunks;
    case 4: return data;
    case 5: return checksumSha256;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fileId = (java.lang.CharSequence)value$; break;
    case 1: fileName = (java.lang.CharSequence)value$; break;
    case 2: chunkIndex = (java.lang.Integer)value$; break;
    case 3: totalChunks = (java.lang.Integer)value$; break;
    case 4: data = (java.nio.ByteBuffer)value$; break;
    case 5: checksumSha256 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'fileId' field.
   * @return The value of the 'fileId' field.
   */
  public java.lang.CharSequence getFileId() {
    return fileId;
  }

  /**
   * Sets the value of the 'fileId' field.
   * @param value the value to set.
   */
  public void setFileId(java.lang.CharSequence value) {
    this.fileId = value;
  }

  /**
   * Gets the value of the 'fileName' field.
   * @return The value of the 'fileName' field.
   */
  public java.lang.CharSequence getFileName() {
    return fileName;
  }

  /**
   * Sets the value of the 'fileName' field.
   * @param value the value to set.
   */
  public void setFileName(java.lang.CharSequence value) {
    this.fileName = value;
  }

  /**
   * Gets the value of the 'chunkIndex' field.
   * @return The value of the 'chunkIndex' field.
   */
  public java.lang.Integer getChunkIndex() {
    return chunkIndex;
  }

  /**
   * Sets the value of the 'chunkIndex' field.
   * @param value the value to set.
   */
  public void setChunkIndex(java.lang.Integer value) {
    this.chunkIndex = value;
  }

  /**
   * Gets the value of the 'totalChunks' field.
   * @return The value of the 'totalChunks' field.
   */
  public java.lang.Integer getTotalChunks() {
    return totalChunks;
  }

  /**
   * Sets the value of the 'totalChunks' field.
   * @param value the value to set.
   */
  public void setTotalChunks(java.lang.Integer value) {
    this.totalChunks = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'checksumSha256' field.
   * @return The value of the 'checksumSha256' field.
   */
  public java.lang.CharSequence getChecksumSha256() {
    return checksumSha256;
  }

  /**
   * Sets the value of the 'checksumSha256' field.
   * @param value the value to set.
   */
  public void setChecksumSha256(java.lang.CharSequence value) {
    this.checksumSha256 = value;
  }

  /**
   * Creates a new FileChunk RecordBuilder.
   * @return A new FileChunk RecordBuilder
   */
  public static com.mars.apacheavro.dto.FileChunk.Builder newBuilder() {
    return new com.mars.apacheavro.dto.FileChunk.Builder();
  }

  /**
   * Creates a new FileChunk RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FileChunk RecordBuilder
   */
  public static com.mars.apacheavro.dto.FileChunk.Builder newBuilder(com.mars.apacheavro.dto.FileChunk.Builder other) {
    return new com.mars.apacheavro.dto.FileChunk.Builder(other);
  }

  /**
   * Creates a new FileChunk RecordBuilder by copying an existing FileChunk instance.
   * @param other The existing instance to copy.
   * @return A new FileChunk RecordBuilder
   */
  public static com.mars.apacheavro.dto.FileChunk.Builder newBuilder(com.mars.apacheavro.dto.FileChunk other) {
    return new com.mars.apacheavro.dto.FileChunk.Builder(other);
  }

  /**
   * RecordBuilder for FileChunk instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FileChunk>
    implements org.apache.avro.data.RecordBuilder<FileChunk> {

    private java.lang.CharSequence fileId;
    private java.lang.CharSequence fileName;
    private int chunkIndex;
    private int totalChunks;
    private java.nio.ByteBuffer data;
    private java.lang.CharSequence checksumSha256;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mars.apacheavro.dto.FileChunk.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fileId)) {
        this.fileId = data().deepCopy(fields()[0].schema(), other.fileId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fileName)) {
        this.fileName = data().deepCopy(fields()[1].schema(), other.fileName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.chunkIndex)) {
        this.chunkIndex = data().deepCopy(fields()[2].schema(), other.chunkIndex);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.totalChunks)) {
        this.totalChunks = data().deepCopy(fields()[3].schema(), other.totalChunks);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.data)) {
        this.data = data().deepCopy(fields()[4].schema(), other.data);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.checksumSha256)) {
        this.checksumSha256 = data().deepCopy(fields()[5].schema(), other.checksumSha256);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FileChunk instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mars.apacheavro.dto.FileChunk other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.fileId)) {
        this.fileId = data().deepCopy(fields()[0].schema(), other.fileId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fileName)) {
        this.fileName = data().deepCopy(fields()[1].schema(), other.fileName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.chunkIndex)) {
        this.chunkIndex = data().deepCopy(fields()[2].schema(), other.chunkIndex);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.totalChunks)) {
        this.totalChunks = data().deepCopy(fields()[3].schema(), other.totalChunks);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.data)) {
        this.data = data().deepCopy(fields()[4].schema(), other.data);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.checksumSha256)) {
        this.checksumSha256 = data().deepCopy(fields()[5].schema(), other.checksumSha256);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'fileId' field.
      * @return The value.
      */
    public java.lang.CharSequence getFileId() {
      return fileId;
    }

    /**
      * Sets the value of the 'fileId' field.
      * @param value The value of 'fileId'.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder setFileId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.fileId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fileId' field has been set.
      * @return True if the 'fileId' field has been set, false otherwise.
      */
    public boolean hasFileId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fileId' field.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder clearFileId() {
      fileId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fileName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFileName() {
      return fileName;
    }

    /**
      * Sets the value of the 'fileName' field.
      * @param value The value of 'fileName'.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder setFileName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fileName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fileName' field has been set.
      * @return True if the 'fileName' field has been set, false otherwise.
      */
    public boolean hasFileName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fileName' field.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder clearFileName() {
      fileName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'chunkIndex' field.
      * @return The value.
      */
    public java.lang.Integer getChunkIndex() {
      return chunkIndex;
    }

    /**
      * Sets the value of the 'chunkIndex' field.
      * @param value The value of 'chunkIndex'.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder setChunkIndex(int value) {
      validate(fields()[2], value);
      this.chunkIndex = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'chunkIndex' field has been set.
      * @return True if the 'chunkIndex' field has been set, false otherwise.
      */
    public boolean hasChunkIndex() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'chunkIndex' field.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder clearChunkIndex() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalChunks' field.
      * @return The value.
      */
    public java.lang.Integer getTotalChunks() {
      return totalChunks;
    }

    /**
      * Sets the value of the 'totalChunks' field.
      * @param value The value of 'totalChunks'.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder setTotalChunks(int value) {
      validate(fields()[3], value);
      this.totalChunks = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'totalChunks' field has been set.
      * @return True if the 'totalChunks' field has been set, false otherwise.
      */
    public boolean hasTotalChunks() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'totalChunks' field.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder clearTotalChunks() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[4], value);
      this.data = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder clearData() {
      data = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'checksumSha256' field.
      * @return The value.
      */
    public java.lang.CharSequence getChecksumSha256() {
      return checksumSha256;
    }

    /**
      * Sets the value of the 'checksumSha256' field.
      * @param value The value of 'checksumSha256'.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder setChecksumSha256(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.checksumSha256 = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'checksumSha256' field has been set.
      * @return True if the 'checksumSha256' field has been set, false otherwise.
      */
    public boolean hasChecksumSha256() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'checksumSha256' field.
      * @return This builder.
      */
    public com.mars.apacheavro.dto.FileChunk.Builder clearChecksumSha256() {
      checksumSha256 = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FileChunk build() {
      try {
        FileChunk record = new FileChunk();
        record.fileId = fieldSetFlags()[0] ? this.fileId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fileName = fieldSetFlags()[1] ? this.fileName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.chunkIndex = fieldSetFlags()[2] ? this.chunkIndex : (java.lang.Integer) defaultValue(fields()[2]);
        record.totalChunks = fieldSetFlags()[3] ? this.totalChunks : (java.lang.Integer) defaultValue(fields()[3]);
        record.data = fieldSetFlags()[4] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[4]);
        record.checksumSha256 = fieldSetFlags()[5] ? this.checksumSha256 : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FileChunk>
    WRITER$ = (org.apache.avro.io.DatumWriter<FileChunk>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FileChunk>
    READER$ = (org.apache.avro.io.DatumReader<FileChunk>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
